# Exploring Proteins in the PDB

In [1]:
import pandas as pd
from tqdm import tqdm

In [2]:
data_path = '/home/ben/peptide_design/datasets/pdb_2021aug02_sample/list.csv'

In [3]:
# df = pd.read_csv(data_path)

In [4]:
from components.encoder import encode_protein_sequence

one_hot_rep, padding_mask, padding_mask_2d, attention_mask = encode_protein_sequence('AAAAA', 5)

In [5]:
attention_mask

tensor([[False,  True,  True,  True,  True],
        [False, False,  True,  True,  True],
        [False, False, False,  True,  True],
        [False, False, False, False,  True],
        [False, False, False, False, False]])

In [6]:
import torch

In [7]:
attention_mask = torch.ones(5, 5)
attention_mask = torch.triu(attention_mask, diagonal=1).bool()

In [8]:
attention_mask

tensor([[False,  True,  True,  True,  True],
        [False, False,  True,  True,  True],
        [False, False, False,  True,  True],
        [False, False, False, False,  True],
        [False, False, False, False, False]])

In [12]:
m = torch.rand(3, 5)

In [13]:
m

tensor([[0.4769, 0.3368, 0.5442, 0.5950, 0.5037],
        [0.1312, 0.6574, 0.6643, 0.5052, 0.5415],
        [0.2247, 0.6777, 0.7025, 0.2458, 0.1125]])

In [20]:
torch.softmax_(m, -1)
m

AttributeError: module 'torch' has no attribute 'softmax_'

In [17]:
s

tensor([[0.1964, 0.1707, 0.2101, 0.2210, 0.2017],
        [0.1359, 0.2300, 0.2316, 0.1976, 0.2049],
        [0.1639, 0.2578, 0.2643, 0.1674, 0.1465]])

In [18]:
s.sum(0)

tensor([0.4962, 0.6586, 0.7060, 0.5860, 0.5531])

In [28]:
org = torch.arange(4 * 9).reshape(4, 9)

In [29]:
org

tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23, 24, 25, 26],
        [27, 28, 29, 30, 31, 32, 33, 34, 35]])

In [30]:
org.reshape(3, 4, 3)

tensor([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8],
         [ 9, 10, 11]],

        [[12, 13, 14],
         [15, 16, 17],
         [18, 19, 20],
         [21, 22, 23]],

        [[24, 25, 26],
         [27, 28, 29],
         [30, 31, 32],
         [33, 34, 35]]])

In [31]:
org.shape()

TypeError: 'torch.Size' object is not callable